### ISSUE TITLE
Unable to queue a song

### ISSUE THREAD

**Issue by Johnathan-Aretos** [KrauseFx/auxcord.org#46]
Hi, 

I'm able to queue a song in the UI from the `user` page, but it won't actually queue. Are you seeing any logs on your side we can debug with?

**Comment by Johnathan-Aretos** [comment]
The problem seems to have been fixed now and all is working as expected. I'm thinking maybe it was a NYE influx of requests on Sonos/Spotify or auxcord's side

**Comment by KrauseFx** [comment]
Thanks - yah I was using it successfully last night also
